#!/bin/bash

--VERSION() {
  echo "github-release v1.3.0."
}

GENERATE_POST_BODY() {
  cat <<EOF
{
  "tag_name": "$NEXT_RELEASE",
  "target_commitish": "master",
  "name": "$NEXT_RELEASE",
  "body": $FORMAT_CONTENT,
  "draft": true,
  "prerelease": false
}
EOF
}

CAPITALIZE() {
  first_capital="$(echo "$1"|cut -c1|tr '[:lower:]' '[:upper:]' )"
  rest_regular="$(echo "$1"|cut -c2-)"
  echo "$first_capital$rest_regular"
}

HORIZONTAL_LINE() {
  printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
}

SHOW_HELP() {
  cat <<EOF
Usage:
  github-release --version
  github-release [-p]
  github-release [-h]

Options:
  --version Print version.
  -p        Show a preview of the changelog without releasing a new version.
  -h        Show this list describing usage and options.
EOF
}

CREATE_CHANGELOG() {

  # Definition of default commit types
  COMMIT_TYPES=( breaking bugfix feature frontend backend workflow testing documentation internal )

  # String to accumulate changelog
  CONTENT=""

  # Get all commits with type annotations and make them paragraphs.
  for TYPE in "${COMMIT_TYPES[@]}"
    do
      if [ -z "$1" ]
        then
          PARAGRAPH="$(git log --format="* %s (%h)" --grep="^\[${TYPE}\]")"
        else
          PARAGRAPH="$(git log "$1"..HEAD --format="* %s (%h)" --grep="^\[${TYPE}\]")"
      fi
      if [ ! -z "$PARAGRAPH" ]
        then
          TITLE="$(CAPITALIZE "$TYPE")"
          PARAGRAPH="${PARAGRAPH//\[$TYPE\] /}"
          CONTENT="$CONTENT## $TITLE\n\n$PARAGRAPH\n\n"
      fi
    done

  # Regex used to find commits without types
  TYPES_REGEX=""
  for TYPE in "${COMMIT_TYPES[@]}"
    do
      TYPES_REGEX="$TYPES_REGEX\[$TYPE\]\|"
  done
  TYPES_REGEX="$TYPES_REGEX\[skip-changelog\]"

  # Get all commit without type annotation and make them another paragraph.
  if [ -z "$1" ]
    then
      PARAGRAPH="$(git log --format=";* %s (%h);")"
    else
      PARAGRAPH="$(git log "$1"..HEAD --format=";* %s (%h);")"
  fi
  OIFS="$IFS"
  IFS=";"
  FILTERED_PARAGRAPH=""
  for COMMIT in $PARAGRAPH
   do
     TRIMMED_COMMIT="$(echo "$COMMIT" | xargs)"
    if [ ! -z "$TRIMMED_COMMIT" ] && ! echo "$TRIMMED_COMMIT" | grep -q "$TYPES_REGEX"
      then
        FILTERED_PARAGRAPH="$FILTERED_PARAGRAPH$TRIMMED_COMMIT\n"
    fi
  done
  IFS="$OIFS"

  # Only add to content if there are commits without type annotations.
  if [ ! -z "$FILTERED_PARAGRAPH" ]
   then
     CONTENT="$CONTENT## Other\n\n$FILTERED_PARAGRAPH\n\n"
  fi

  # Output changelog
  echo -e "$CONTENT"
}

#
# Main script
#

if [ "$1" == "--version" ]
  then
    --VERSION
    exit 0
fi

# Exit if not in a Git repository.
if [ "true" != "$(git rev-parse --is-inside-work-tree 2> /dev/null)" ]
  then
    echo -e "This does not seem to be a Git repository.\n"
    exit
fi

# Parse all options
while getopts ":ph" OPTION
  do
    case $OPTION in
      p)
        PREVIEW=true
        ;;
      h)
        SHOW_HELP
        exit
        ;;
      \?)
        echo "Invalid option: -$OPTARG"
        exit
        ;;
    esac
done

# Generate changelog either from last tag or from beginning
if [ -z "$(git tag)" ]
  then
    CONTENT=$(CREATE_CHANGELOG)
  else
    LATEST_RELEASE="$(git describe --tags --abbrev=0)"
    CONTENT=$(CREATE_CHANGELOG "${LATEST_RELEASE}")
fi


if [ -z "$CONTENT" ]
  then
    echo -e "No changes made since last release $LATEST_RELEASE."
	exit
fi

# In preview mode, show changelog and exit
if [ "$PREVIEW" = true ]
  then
    HORIZONTAL_LINE
    echo "$CONTENT"
    HORIZONTAL_LINE
  exit
fi

# obtain remote repository details
function get_repository_details
{
  read -r -p 'Repository URL > ' REPO_URL
  read -r -p 'Default Branch > ' REPO_BRANCH
}

GREY_COLOR="\033[0;37m"
NO_COLOR="\033[0m"

# if origin isn't set
if [[ ! $(git config --get remote.origin.url) ]]
  then
    echo -e "Remote ${GREY_COLOR}origin${NO_COLOR} missing"
    echo -e "You need to specify the remote repository manually"
    get_repository_details
    git remote add origin "${REPO_URL}" -m "${REPO_BRANCH}"
    echo -e "Remote ${GREY_COLOR}origin${NO_COLOR} set successfully"
fi

# Obtained valid 'origin' remote, set REPOSITORY now
REPOSITORY=$(git config --get remote.origin.url | sed -E 's/https?:\/\/(www.)?github.com\/|git@github.com:([A-Za-z]+\/[A-Za-z]+)/\2/')

echo -e "Detected remote repository ${GREY_COLOR}${REPOSITORY}${NO_COLOR}."

if [ -z "$(git tag)" ]
  then
    echo -e "This seems to be its first release. Congratulations!"
  else
    echo -e "Its latest release is ${GREY_COLOR}${LATEST_RELEASE}${NO_COLOR}."
fi

echo -e "What version would you like to release? "

read -r NEXT_RELEASE

FORMAT_CONTENT=$(node -p -e 'JSON.stringify(process.argv[1])' "${CONTENT}")

RELEASE=$(curl --silent -H "Content-Type: application/json" -X POST --data "$(GENERATE_POST_BODY)" "https://api.github.com/repos/${REPOSITORY}/releases?access_token=${AUTOMATIC_RELEASE_GITHUB_TOKEN}")

EDIT_URL="$(node -p -e 'JSON.parse(process.argv[1]).html_url.replace('/\\/tag\\//', '/edit/')' "${RELEASE}")"

open "$EDIT_URL"
